# fly.toml app configuration file generated for collectivae on 2025-01-17T21:31:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'collectivae'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_PATH = '/usr/home/data/db.sqlite'

[[mounts]]
  source = 'myapp_data'
  destination = '/usr/home/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
